### ISSUE TITLE
Error for build - RCTUITextField.h file not found

### ISSUE THREAD

**Issue by brunoosilva** [ivanzotov/react-native-text-input-mask#2]
Hello,

Error for build:

**RCTUITextField.h file not found**

Version: 
react-native - 0.44.2

**Comment by hiaw** [comment]
I also had this problem. After a bit of investigation it seems you would need to be on react native 0.47 to use this because `RCTUITextField.h` was added then.

https://github.com/facebook/react-native/releases/tag/v0.47.0

**Comment by ivanzotov** [comment]
Yes, it works for 0.47+, I will add this info to README.
